{{- if eq .Values.postgres.include true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-postgres-svc
spec:
  selector:
    app: {{ .Release.Name }}-api-postgres
  ports:
    - name: db-tcp
      port: {{ .Values.postgres.port | default 5432 }}
      targetPort: {{ .Values.postgres.port | default 5432 }}
      protocol: TCP
{{- end }}
