version: '3'
services:
  rabbitmq:
    container_name: sv-rabbit
    image: rabbitmq:3-management
    ports:
      - 8080:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: sv
      RABBITMQ_DEFAULT_PASS: sv
  postgres:
    container_name: sv-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=local
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
