apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  PORT: {{ required "A valid value for env.port must be provided" .Values.env.port | quote }}
  CLIENT_URL: {{ required "A valid value for env.clientUri must be provided" .Values.env.clientUri }}

  AWS_REGION: {{ required "A valid value for cognito.region must be provided" .Values.cognito.region }}
  AWS_USER_POOLS_ID: {{ required "A valid value for cognito.userPoolId must be provided" .Values.cognito.userPoolId }}

  RABBIT_MQ_HOST: {{ required "A valid value for rabbitmq.host must be provided" .Values.rabbitmq.host }}
  RABBIT_MQ_PORT: {{ .Values.rabbitmq.port | default "5672" | quote }}
  RABBIT_MQ_USER: {{ required "A valid value for rabbit.username must be provided" .Values.rabbitmq.auth.username }}
  RABBIT_MQ_PASS: {{ required "A valid value for rabbit.password must be provided" .Values.rabbitmq.auth.password }}

  POSTGRES_HOST: {{ required "A valid value for postgres.host must be provided" .Values.postgres.host }}
  POSTGRES_PORT: {{ .Values.postgres.port | default "5432" | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | default "sv" }}
  POSTGRES_PASS: {{ .Values.postgres.password | default "sv" }}
  POSTGRES_DB: {{ .Values.env.dbName | default "sv" }}
{{- if eq .Values.postgres.ssl true }}
  POSTGRES_REQUIRE_SSL: "true"
{{- end }}
