apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.api.registry }}:{{ .Values.api.version }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 50m
              memory: 80Mi
          ports:
            - name: http
              containerPort: 80
          env:
            - name: VERSION_TAG
              value: {{ .Values.api.version }}
          envFrom:
            - secretRef:
                name: {{ .Values.api.secretName }}
