apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-svc
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - port: {{ .Values.env.port }}
      name: http
      targetPort: 80
