apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtual-service
spec:
  hosts:
  - {{ required "A valid value for env.host must be provided" .Values.env.host | quote }}
  gateways:
  - {{ .Values.gateway.include | ternary (print .Release.Name "-gateway") .Values.gateway.name }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{ required "A valid value for env.port must be provided" .Values.env.port }}
        host: {{ .Release.Name }}-svc
