version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME $DOCKER_REGISTRY_URL --password-stdin
      - checkout
      - run: |
          REGISTRY=$(echo $DOCKER_REGISTRY_URL/$DOCKER_USERNAME/stingyvegan-api/stingyvegan-api)
          echo $REGISTRY
          TAG=$(echo $CIRCLE_SHA1 | cut -c -7)
          echo $TAG
          docker build -t $REGISTRY:$TAG .
