version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run: |
          docker login -u $DOCKER_USERNAME -p DOCKER_PASSWORD DOCKER_REGISTRY_URL
      - checkout
      - run: |
          TAG=$(echo $CIRCLE_SHA1 | cut -c -7)
          docker build -t stingyvegan:$TAG .
